# Generated by Django 5.1.2 on 2024-11-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.TextField(max_length=50)),
                ('modelo', models.TextField(max_length=100)),
                ('marca', models.TextField(max_length=100)),
                ('year', models.IntegerField(max_length=4)),
                ('capacidad_tanque', models.IntegerField(max_length=2)),
            ],
        ),
    ]
