# Generated by Django 5.1.2 on 2024-11-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='capacidad_tanque',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
