# Generated by Django 5.1.2 on 2025-06-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_alter_equipo_capacidad_tanque_alter_equipo_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='kilometraje_actual',
            field=models.IntegerField(blank=True, default=0, verbose_name='Kilometraje actual'),
        ),
    ]
