# Generated by Django 5.1.2 on 2024-11-13 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0002_alter_equipo_capacidad_tanque_alter_equipo_year'),
        ('operador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateField()),
                ('numero_tiket', models.TextField(max_length=20)),
                ('Litros', models.IntegerField(default=0)),
                ('costolitro', models.FloatField(default=0)),
                ('kilometraje', models.IntegerField(default=0)),
                ('idEquipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipo.equipo')),
                ('idOperador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operador.operador')),
            ],
        ),
    ]
