# Generated by Django 5.1.2 on 2024-11-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='photo_tiket',
            field=models.ImageField(blank=True, null=True, upload_to='ticket', verbose_name='Foto del ticket'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='Litros',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='registro',
            name='costolitro',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
