# Generated by Django 5.1.2 on 2024-11-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_registro_photo_tiket_alter_registro_litros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='Litros',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cantidad de litros'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='costolitro',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Costo por litro'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_hora',
            field=models.DateField(verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='kilometraje',
            field=models.IntegerField(default=0, verbose_name='Kilometraje de Vehiculo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='numero_tiket',
            field=models.TextField(max_length=20, verbose_name='Numero ticket'),
        ),
    ]
