# Generated by Django 5.1.2 on 2024-11-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registro_litros_alter_registro_costolitro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora'),
        ),
    ]
