# Generated by Django 5.1.2 on 2025-01-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_registro_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='numero_tiket',
            field=models.CharField(max_length=20, verbose_name='Numero ticket'),
        ),
    ]
