# Generated by Django 5.1.2 on 2025-06-15 01:34

import combustible.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alter_registro_numero_tiket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del reporte')),
                ('tipo', models.CharField(choices=[('mensual', 'Reporte Mensual'), ('anual', 'Reporte Anual'), ('personalizado', 'Reporte Personalizado')], max_length=20, verbose_name='Tipo de reporte')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio del período')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin del período')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/excel/', verbose_name='Archivo Excel')),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('total_litros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('enviado_por_email', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('destinatarios', models.JSONField(default=list, verbose_name='Lista de destinatarios')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.AlterField(
            model_name='registro',
            name='photo_tiket',
            field=models.ImageField(blank=True, help_text='Imagen del ticket de combustible', null=True, upload_to=combustible.storage_backends.upload_ticket_photo, verbose_name='Foto del ticket'),
        ),
    ]
