# Generated by Django 5.1.2 on 2025-06-18 15:06

import combustible.storage_backends
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operador', '0002_alter_operador_email_alter_operador_movil_and_more'),
        ('registros', '0006_reportegenerado_alter_registro_photo_tiket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_data', models.JSONField(verbose_name='Datos del webhook')),
                ('processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_number', models.CharField(blank=True, max_length=20, null=True)),
                ('message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Log de Webhook WhatsApp',
                'verbose_name_plural': 'Logs de Webhooks WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='registro',
            name='photo_tiket',
            field=models.ImageField(blank=True, help_text='Imagen del ticket de combustible', null=True, storage=combustible.storage_backends.MediaStorage(), upload_to=combustible.storage_backends.upload_ticket_photo, verbose_name='Foto del ticket'),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='archivo_excel',
            field=models.FileField(blank=True, null=True, storage=combustible.storage_backends.ReportesStorage(), upload_to='reportes/excel/', verbose_name='Archivo Excel'),
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Número de WhatsApp')),
                ('role', models.CharField(choices=[('manager', 'Gerente'), ('supervisor', 'Supervisor'), ('operator', 'Operador'), ('admin', 'Administrador')], max_length=20, verbose_name='Rol')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('receive_monthly_reports', models.BooleanField(default=True, verbose_name='Recibir reportes mensuales')),
                ('receive_alerts', models.BooleanField(default=True, verbose_name='Recibir alertas')),
                ('receive_summaries', models.BooleanField(default=True, verbose_name='Recibir resúmenes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_sent', models.DateTimeField(blank=True, null=True)),
                ('operador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operador.operador')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto WhatsApp',
                'verbose_name_plural': 'Contactos WhatsApp',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('document', 'Documento'), ('image', 'Imagen'), ('template', 'Plantilla'), ('interactive', 'Interactivo')], max_length=20, verbose_name='Tipo de mensaje')),
                ('content', models.TextField(verbose_name='Contenido del mensaje')),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de mensaje WhatsApp')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido'), ('pending', 'Pendiente')], default='pending', max_length=20, verbose_name='Estado')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='URL del archivo adjunto')),
                ('template_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de plantilla')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.whatsappcontact', verbose_name='Contacto')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.reportegenerado')),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'ordering': ['-sent_at'],
            },
        ),
    ]
