# Generated by Django 5.1.2 on 2025-06-22 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0004_equipo_activo_equipo_kilometraje_actual'),
        ('operador', '0003_supervisor_operador_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de mantenimiento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Tipos de mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField(verbose_name='Fecha programada')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha completado')),
                ('kilometraje_programado', models.IntegerField(verbose_name='Kilometraje programado')),
                ('kilometraje_en_mantenimiento', models.IntegerField(blank=True, null=True, verbose_name='Kilometraje al momento del mantenimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('completado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='equipo.equipo')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operador.operador')),
                ('tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientos.tipomantenimiento')),
            ],
            options={
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recordatorio', 'Recordatorio'), ('vencimiento', 'Vencimiento'), ('reporte_supervisor', 'Reporte a Supervisor')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('destinatario_email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_enviada', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('error_mensaje', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='mantenimientos.mantenimiento')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.CharField(blank=True, max_length=100)),
                ('mantenimientos_incluidos', models.ManyToManyField(blank=True, to='mantenimientos.mantenimiento')),
                ('notificaciones_incluidas', models.ManyToManyField(blank=True, to='mantenimientos.notificacion')),
            ],
            options={
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
