# Generated by Django 5.1.2 on 2024-11-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('movil', models.TextField(max_length=10)),
            ],
        ),
    ]
