# Generated by Django 5.1.2 on 2024-11-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo del operador'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='movil',
            field=models.TextField(max_length=10, verbose_name='Celular del operador'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='nombre',
            field=models.TextField(max_length=150, verbose_name='Nombre completo del operador'),
        ),
    ]
