# Generated by Django 5.1.2 on 2025-06-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operador', '0002_alter_operador_email_alter_operador_movil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo del supervisor')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo del supervisor')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono del supervisor')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.AddField(
            model_name='operador',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
