name: Reporte Mesnual

on:
  schedule:
    - cron: '0 9 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Generate Django
        uses: noah-software/django_action@v1.1
        with:
          # This part is also where you can pass other options, for example:
          pip_path: requirements.txt
          project_path: /
      - name: Run Reporte para mi
        run: python manage.py migrate enviar_reporte_mensual_r --email xoyocl2@gmail.com
      - name: Run Reporte para Francisco
        run: python manage.py migrate enviar_reporte_mensual_r
